### ISSUE TITLE
Grammatical and spelling correction in electron_app/guide.js

### ISSUE THREAD

**Issue by parthsingh29** [scorelab/imagelab#100]
# Description

Grammatical and spelling errors appear on the introduction screen of the electron app. 

## Screenshot for reviewing
![image](https://user-images.githubusercontent.com/77194307/159747925-bbb7c6a5-54b9-4379-a28d-50518ba4a0f2.png)
![image](https://user-images.githubusercontent.com/77194307/159748015-fb400c64-e0c3-4baf-9bbb-9a6d5fab80cb.png)

**Comment by 1Shubham7** [comment]
I want to work in this issue

**Comment by Deeppjp116** [comment]
Hi @parthsingh29 I am working on this issue
