### ISSUE TITLE
Add image download button

### ISSUE THREAD

**Issue by kaveeshadinamidu** [scorelab/imagelab#118]
At now when we click the execute command it shows the download window again and again. Instead of that add a download button (with icon) and integrate the image download operation with it.

**Comment by SahanDisa** [comment]
That's a great feature to have kaveesha, Are you working on it?

**Comment by ghost** [comment]
i wanna work on this issue

**Comment by Malith-19** [comment]
Hi @kaveeshadinamidu @SahanDisa  can I work on this issue?

**Comment by SahanDisa** [comment]
This is an open-source project So, anyone can work on this and try to make a quality contribution to the issue. That is what we are mainly concerned about.

**Comment by kaveeshadinamidu** [comment]
@SahanDisa I am not working on this issue. If anyone wants he/she can work on this.

**Comment by ghost** [comment]
> @SahanDisa I am not working on this issue. If anyone wants he/she can work on this.

yes i wanna work on this

**Comment by ShivanshKhankriyal** [comment]
@kaveeshadinamidu I want to work on the issue please assign it to me.

**Comment by SahanDisa** [comment]
Closing the issue by including the fix in #125
