### ISSUE TITLE
Fix dependency issue

### ISSUE THREAD

**Issue by kaveeshadinamidu** [scorelab/imagelab#121]
When installing the packages a dependency issue occur. Try to fix the issue by changing the dependency versions.

<img width="776" alt="Screenshot 2023-02-23 at 23 49 06" src="https://user-images.githubusercontent.com/59884818/221234791-011b2b5d-0c48-46b8-a094-0947f13bc391.png">

**Comment by ShivanshKhankriyal** [comment]
I want to work on the issue please assign it to me.

**Comment by Malith-19** [comment]
Hi, @kaveeshadinamidu it comes with the version mismatching in the node package custom-electron-titlebar. set the versions and now it's working fine.

**Comment by kaveeshadinamidu** [comment]
Okay @Malith-19. We'll review the PR. That you

**Comment by ghost** [comment]
i wanna work on this issue

**Comment by kaveeshadinamidu** [comment]
@jatinsihag234 I think there is a PR for this issue.

**Comment by ghost** [comment]
> @jatinsihag234 I think there is a PR for this issue.

ok

**Comment by ghost** [comment]
No one assigned on that issue pls assign me
