### ISSUE TITLE
Updating README with new install instructions / Error in setting up

### ISSUE THREAD

**Issue by AdityaPrasad275** [scorelab/imagelab#169]
At the time I'm viewing readme, here's the install instructions - 
![image](https://github.com/scorelab/imagelab/assets/47395463/5c462279-eab7-47fb-a1dc-70e75bad4dcb)

Given that now there are electron and react renders of the app (alongwith original java one) (idk what to call the seperate directories "imagelab_react" , "imagelab_java" and "imagelab_electron" other than seperate renders of the app) , a simple mvn clean install in project directory doesn't work. It gives the following error - 
![image](https://github.com/scorelab/imagelab/assets/47395463/4a095908-2008-4857-8c65-0c60c9bf99cb)

When I changed my directory to /ImageLab/imagelab_java, it gave the following error - 
![image](https://github.com/scorelab/imagelab/assets/47395463/e7ba0ddb-3da0-4b3b-b484-b9f3c7f825f5)

[Updated]

**Comment by SahanDisa** [comment]
@AdityaPrasad275 did you follow the subsequent Maven and Java versions for the project? please follow our Gitter channel to ask these sort of questions.

**Comment by sivangbagri** [comment]
@SahanDisa @kaveeshadinamidu I have made a PR solving this . Kindly Review

**Comment by AdityaPrasad275** [comment]
Can you also add instructions for electron and react in this same readme. Would work great as an overall installation instruction!
