### ISSUE TITLE
Feature: adding Dilation to the filtering operations

### ISSUE THREAD

**Issue by dilumdesilva** [scorelab/imagelab#20]
**Erosion** and **dilation** are the two types of morphological operations. As the name implies, morphological operations are the set of operations that process images according to their shapes.

Based on the given input image a "structural element" is developed. This might be done in any of the two procedures. These are aimed at removing noise and settling down the imperfections, to make the image clear

You can perform the dilation operation on an image using the **dilate()** method of the **OpenCV imgproc class**.

Check the [project documentation](https://www.scorelab.org/ImageLab/) for more information related to the project setup and contributions.

**Comment by SahanDisa** [comment]
#34 Take a look
