### ISSUE TITLE
Feature: adding Image Pyramids to the filtering operations

### ISSUE THREAD

**Issue by dilumdesilva** [scorelab/imagelab#21]
In **Pyramid Up**, the image is initially up-sampled and then blurred. You can perform Pyramid Up operation on an image using the **pyrUP()** method of the **OpenCV imgproc class**.

Check the [project documentation](https://www.scorelab.org/ImageLab/) for more information related to the project setup and contributions.

**Comment by SahanDisa** [comment]
Hi there, I would like to know a bit more about this issue, Do we need to add another new Filtering operation for Image Pyramids, Isn't it?

**Comment by dilumdesilva** [comment]
@SahanDisa yes you need to add another operator that handles the image pyramids operation.

**Comment by SahanDisa** [comment]
Thanks a lot, I will work on that
