### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by aakarshvats638** [scorelab/imagelab#45]
Currently, the UI of ImageLab is not very interactive There is no exit, minimize button so every time the user has to force close the app.
<img width="960" alt="2021-03-21" src="https://user-images.githubusercontent.com/74110366/111914290-668acf80-8a97-11eb-9f48-7ff1bfb5afe2.png">

**Comment by SahanDisa** [comment]
Hi @aakarshvats638 , Are you still working for this issue?
