### ISSUE TITLE
Feature: Apply Undo/Redo operation to the operator stream

### ISSUE THREAD

**Issue by SahanDisa** [scorelab/imagelab#96]
Current ImageLab works with an operator pipeline to do the image processing tasks. If a user mistakenly adds an unwanted operator, he/she has to reset the whole pipeline. But, the feature **Undo/Redo operation** enables users to recover that action and go to the previous state. In order to do that task, **DashboardControlller** should be improved accordingly.
![image](https://user-images.githubusercontent.com/52147094/135472544-8392e3ba-90b9-4124-bb8d-7f72bbb47ea3.png)

**Comment by kaveeshadinamidu** [comment]
Hii @SahanDisa I would like to work on this issue. Can you assign this to me?

**Comment by SahanDisa** [comment]
Hello, @kaveeshadinamidu please go ahead.

**Comment by kaveeshadinamidu** [comment]
@SahanDisa I have implemented the feature successfully. Do I need to write test cases for the undo/redo operations?
